---

- hosts: relays
  vars:
    #tor_ContactInfo: relayor-example@example.com
    tor_config:
      SigningKeyLifetime: 90 days
    tor_nickname: "{{ ansible_hostname }}"
    tor_ports:
        - { orport: 443, dirport: 80}
  roles:
   - nusenu.relayor
