---

- hosts: relays
  vars:
    #tor_ContactInfo: relayor-example@example.com
    tor_config:
      SigningKeyLifetime: 90 days
    tor_nickname: "{{ ansible_hostname }}"
    tor_maxPublicIPs: 2
    tor_alpha: True
  roles:
   - nusenu.relayor
